services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      # Mount Home Assistant configuration
      # - ./home-assistant/config:/config
      - ${HA_HOME}/${HA_CONFIG}:/config
      # Synchronize time with host
      - /etc/localtime:/etc/localtime:ro
      # Mount DBus socket for Home Assistant
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  hass-configurator:
    container_name: hass-configurator
    image: "causticlab/hass-configurator-docker:latest"
    ports:
      - "3218:3218/tcp"
    volumes:
      # - "./hass-configurator/config:/config"
      - ${HA_HOME}/${HA_CONFIGURATOR_CONFIG}:/config
      # - "./home-assistant/config:/hass-config"
      - ${HA_HOME}/${HA_CONFIG}:/hass-config
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      # Expose MQTT port
      - 1883:1883
    volumes:
      # Mount Mosquitto configuration
      # - ./mosquitto/config:/mosquitto/config
      - ${HA_HOME}/${MQTT_CONFIG}:/mosquitto/config
      # Mount Mosquitto data
      # - ./mosquitto/data:/mosquitto/data
      - ${HA_HOME}/${MQTT_DATA}:/mosquitto/data
      # Use system log for Mosquitto logs
      # - mosquitto_log:/mosquitto/log
      - ${HA_HOME}/${MQTT_LOG}:/mosquitto/log
    restart: always

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: zigbee2mqtt
    depends_on:
      # Ensure Mosquitto starts before Zigbee2MQTT
      - mosquitto
    volumes:
      # Mount Zigbee2MQTT data
      # - ./zigbee2mqtt:/app/data
      - ${HA_HOME}/${ZB2MQTT}:/app/data
      # Mount udev for device access
      - /run/udev:/run/udev:ro
      # Synchronize time with host
      - /etc/localtime:/etc/localtime:ro
    ports:
      # Expose Zigbee2MQTT web frontend
      - 8080:8080
    user: "1000:1000"
    group_add:
      - dialout
    devices:
      # Map Zigbee USB dongle to container
      # - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_5a1d8c8c5ffded118e4bfe64024206e6-if00-port0:/dev/ttyUSB0
      - ${DONGLE_PLUS_USB}:/dev/ttyUSB0
    restart: unless-stopped

volumes:
  # Persistent log storage for Mosquitto
  mosquitto_log:

