homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto
serial:
  adapter: ember
  port: /dev/ttyUSB0
  baudrate: 230400
frontend:
  port: 8080
advanced:
  log_level: info
devices:
  '0xa4c1381852800272':
    friendly_name: first_motion_sensor
  '0x0c4314fffe329859':
    friendly_name: Ikea_Tradfri_LED_Driver_Kitchen
